---
abstract: 'DSL around Mojo routing'
author:
  - 'Mons Anderson, C<< <mons at cpan.org> >>'
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  lib::abs: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Routes-DSL
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  MojoX::Routes::DSL:
    file: lib/MojoX/Routes/DSL.pm
    version: 0.01
requires:
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
